language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
env:
  global:
    - NODE_ENV=test
script:
  - npm install
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release || true
