language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t node-blog .
env:
  global:
    - NODE_ENV=test
script:
  - docker run -e CI=true node-blog npm run test
  - docker run -e CI=true node-blog npm run lint
  - docker run -e CI=true node-blog npm run semantic-release || true
