version: "3.8"

services:
  app-dev:
    container_name: median-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: "development"
    env_file:
      - ./src/server/environments/.development.env
    depends_on:
      - postgres
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    tty: true
    command: ["npm", "run", "start:dev"]
    networks:
      - webnet
  # Service to run tests and lints. So removed DB connection
  app-test:
    container_name: median-test
    build:
      context: .
      dockerfile: Dockerfile
      target: "test"
    env_file:
      - ./src/server/environments/.test.env
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=test
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    tty: true
    networks:
      - webnet
  app-prod:
    container_name: median-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: "production"
    env_file:
      - ./src/server/environments/.production.env
    depends_on:
      - postgres
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    tty: true
    command: ["npm", "start"]
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
