version: "3.8"

services:
  app:
    container_name: blog-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/server/environments/.development.env
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    tty: true
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
